Repository TerryIsmael/decide-part-pacodelucia, pull requests merged in 2023-12, with the labels that each got.

#169 Fix: Ruta de stats reparada #159
  decide-frontend/src/components/Stats.vue
Labels: integration

#170 Fix: Eliminada rutas duplicadas en router.js #160
  decide-frontend/src/router.js
Labels: integration

#168 Fix: Eliminados archivos innecesarios #156
  decide/booth/package-lock.json
  node_modules/.package-lock.json
  node_modules/nodejs/1/getmodule.js
  node_modules/nodejs/1/module.js
  node_modules/nodejs/1/singleobject.js
  node_modules/nodejs/package.json
  package-lock.json
  package.json
Labels: integration

#216 Config: Refactorización de contraseña LDAP
  decide/.env.example
  decide/local_settings.example.py
Labels: config

#218 fix: Arreglo en configuracion de import LDAP
  decide/census/views.py
Labels: bug

#261 Fix: Correccionde la posicion del boton stats #259
  decide-frontend/src/components/Home.vue
Labels: interface

#289 Feat:Cambio de color gráfica
  decide-frontend/src/components/GraficaView.vue
Labels: feature, interface
